from django.urls import path

from .views import (
    CommunityAvailabilityMeView,
    CommunityChannelAvailabilityView,
    CommunityChannelDetailView,
    CommunityChannelListCreateView,
    CommunityChannelMemberDetailView,
    CommunityChannelMembersView,
    CommunityChannelMessagesView,
    CommunityChannelNotificationPreferenceView,
    CommunityChannelNotificationsReadView,
    CommunityChannelPinsView,
    CommunityDmListCreateView,
    CommunityDmMessageReactionView,
    CommunityDmMessagesView,
    CommunityDmReadView,
    CommunityHubView,
    CommunityMessageDetailView,
    CommunityMessagePinView,
    CommunityMessageReactionView,
    CommunityMessageReportView,
    CommunityMessageSaveView,
    CommunityMetaView,
    CommunityNotificationListView,
    CommunityNotificationReadAllView,
    CommunityNotificationReadView,
    CommunityReactionMetaView,
    CommunityReportDetailView,
    CommunityReportsListView,
    CommunitySavedListView,
)

urlpatterns = [
    path("community/meta/", CommunityMetaView.as_view(), name="community-meta"),
    path("community/hub/", CommunityHubView.as_view(), name="community-hub"),
    path(
        "community/availability/me/",
        CommunityAvailabilityMeView.as_view(),
        name="community-availability-me",
    ),
    path(
        "community/notifications/",
        CommunityNotificationListView.as_view(),
        name="community-notification-list",
    ),
    path(
        "community/notifications/read-all/",
        CommunityNotificationReadAllView.as_view(),
        name="community-notification-read-all",
    ),
    path(
        "community/notifications/<uuid:notification_id>/read/",
        CommunityNotificationReadView.as_view(),
        name="community-notification-read",
    ),
    path(
        "community/reactions/meta/",
        CommunityReactionMetaView.as_view(),
        name="community-reaction-meta",
    ),
    path(
        "community/reports/",
        CommunityReportsListView.as_view(),
        name="community-report-list",
    ),
    path(
        "community/reports/<uuid:report_id>/",
        CommunityReportDetailView.as_view(),
        name="community-report-detail",
    ),
    path(
        "community/channels/",
        CommunityChannelListCreateView.as_view(),
        name="community-channel-list",
    ),
    path(
        "community/channels/<uuid:channel_id>/",
        CommunityChannelDetailView.as_view(),
        name="community-channel-detail",
    ),
    path(
        "community/channels/<uuid:channel_id>/members/",
        CommunityChannelMembersView.as_view(),
        name="community-channel-members",
    ),
    path(
        "community/channels/<uuid:channel_id>/members/<uuid:user_id>/",
        CommunityChannelMemberDetailView.as_view(),
        name="community-channel-member-detail",
    ),
    path(
        "community/channels/<uuid:channel_id>/availability/",
        CommunityChannelAvailabilityView.as_view(),
        name="community-channel-availability",
    ),
    path(
        "community/channels/<uuid:channel_id>/messages/",
        CommunityChannelMessagesView.as_view(),
        name="community-channel-messages",
    ),
    path(
        "community/channels/<uuid:channel_id>/pins/",
        CommunityChannelPinsView.as_view(),
        name="community-channel-pins",
    ),
    path(
        "community/channels/<uuid:channel_id>/notification-preference/",
        CommunityChannelNotificationPreferenceView.as_view(),
        name="community-channel-notification-preference",
    ),
    path(
        "community/channels/<uuid:channel_id>/notifications/read/",
        CommunityChannelNotificationsReadView.as_view(),
        name="community-channel-notifications-read",
    ),
    path(
        "community/messages/<uuid:message_id>/",
        CommunityMessageDetailView.as_view(),
        name="community-message-detail",
    ),
    path(
        "community/messages/<uuid:message_id>/pin/",
        CommunityMessagePinView.as_view(),
        name="community-message-pin",
    ),
    path(
        "community/messages/<uuid:message_id>/save/",
        CommunityMessageSaveView.as_view(),
        name="community-message-save",
    ),
    path(
        "community/messages/<uuid:message_id>/reactions/",
        CommunityMessageReactionView.as_view(),
        name="community-message-reaction",
    ),
    path(
        "community/messages/<uuid:message_id>/report/",
        CommunityMessageReportView.as_view(),
        name="community-message-report",
    ),
    path(
        "community/saved/",
        CommunitySavedListView.as_view(),
        name="community-saved-list",
    ),
    path("community/dms/", CommunityDmListCreateView.as_view(), name="community-dm-list"),
    path(
        "community/dms/<uuid:conversation_id>/messages/",
        CommunityDmMessagesView.as_view(),
        name="community-dm-messages",
    ),
    path(
        "community/dms/<uuid:conversation_id>/read/",
        CommunityDmReadView.as_view(),
        name="community-dm-read",
    ),
    path(
        "community/dm-messages/<uuid:message_id>/reactions/",
        CommunityDmMessageReactionView.as_view(),
        name="community-dm-message-reaction",
    ),
]
