# Generated by Django 5.1.4 on 2026-07-20 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMediaFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('ghl_folder_id', models.CharField(help_text='GHL media folder id — used as upload parentId.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to='tenancy.location')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['location', 'name'], name='tenancy_loc_locatio_b3bb5b_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'name'), name='unique_location_media_folder_name')],
            },
        ),
    ]
