# Generated by Django 5.1.4 on 2026-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_locationmediafolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permission_denies',
            field=models.JSONField(blank=True, default=list, help_text='Permission codenames revoked from the role.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='permission_grants',
            field=models.JSONField(blank=True, default=list, help_text='Permission codenames granted beyond the role.'),
        ),
    ]
