# Generated by Django 5.1.4 on 2026-07-29 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_membership_permission_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('roi_center', 'ROI Center'), ('success_center', 'Success Center'), ('members', 'Members'), ('locations', 'Locations'), ('agency', 'Agency Management'), ('billing_onboarding', 'Billing & Onboarding'), ('integrations', 'Integrations'), ('other', 'General / Other')], db_index=True, default='other', max_length=32)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('testing', 'Testing'), ('released', 'Released'), ('declined', 'Declined')], db_index=True, default='submitted', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests_created', to=settings.AUTH_USER_MODEL)),
                ('source_agency', models.ForeignKey(blank=True, help_text='Attribution only — not exposed on customer APIs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests_sourced', to='tenancy.agency')),
                ('source_location', models.ForeignKey(blank=True, help_text='Attribution only — not exposed on customer APIs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests_sourced', to='tenancy.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureReleaseNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_release_notes_published', to=settings.AUTH_USER_MODEL)),
                ('feature_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_notes', to='feature.featurerequest')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_comments', to=settings.AUTH_USER_MODEL)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feature.featurerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureStatusEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_status_events', to=settings.AUTH_USER_MODEL)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='feature.featurerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feature.featurerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['status', '-updated_at'], name='feature_fea_status_9776a5_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['category', '-updated_at'], name='feature_fea_categor_add970_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['-created_at'], name='feature_fea_created_4b6484_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['-updated_at'], name='feature_fea_updated_34fd28_idx'),
        ),
        migrations.AddIndex(
            model_name='featurereleasenote',
            index=models.Index(fields=['status', '-published_at'], name='feature_fea_status_6873ad_idx'),
        ),
        migrations.AddIndex(
            model_name='featurereleasenote',
            index=models.Index(fields=['feature_request', 'status'], name='feature_fea_feature_15b5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='featurecomment',
            index=models.Index(fields=['feature_request', 'created_at'], name='feature_fea_feature_a24631_idx'),
        ),
        migrations.AddIndex(
            model_name='featurestatusevent',
            index=models.Index(fields=['feature_request', 'created_at'], name='feature_fea_feature_7c54a8_idx'),
        ),
        migrations.AddIndex(
            model_name='featurevote',
            index=models.Index(fields=['feature_request', 'created_at'], name='feature_fea_feature_69ec5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='featurevote',
            constraint=models.UniqueConstraint(fields=('feature_request', 'user'), name='unique_feature_vote_per_user'),
        ),
    ]
