# Generated by Django 5.1.4 on 2026-07-29 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature", "0001_feature_center_mvp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Existing MVP comments were staff-only — keep them internal.
        migrations.AddField(
            model_name="featurecomment",
            name="is_internal",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True = staff-only note; False = public discussion.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="featurecomment",
            name="is_internal",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True = staff-only note; False = public discussion.",
            ),
        ),
        migrations.AddIndex(
            model_name="featurecomment",
            index=models.Index(
                fields=["feature_request", "is_internal", "created_at"],
                name="feature_fea_feature_fcda14_idx",
            ),
        ),
    ]
