# Generated by Django 5.1.4 on 2026-07-21 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_locationmediafolder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyCourse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('course_type', models.CharField(choices=[('course', 'Course'), ('video', 'Video'), ('article', 'Article'), ('onboarding', 'Onboarding'), ('knowledge_base', 'Knowledge base'), ('learning_path', 'Learning path')], db_index=True, default='course', max_length=32)),
                ('section_key', models.CharField(choices=[('getting_started', 'Getting started'), ('courses', 'Courses'), ('lessons', 'Lessons'), ('knowledge_base', 'Knowledge base'), ('learning_paths', 'Learning paths'), ('how_to_use_service_pilot', 'How to use Service Pilot')], db_index=True, default='courses', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('featured', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, default='', max_length=1024)),
                ('download_url', models.URLField(blank=True, default='', max_length=1024)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1024)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCourseCompletion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_lesson_count', models.PositiveIntegerField(default=0)),
                ('total_lesson_count', models.PositiveIntegerField(default=0)),
                ('percent_complete', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='academy.academycourse')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_course_completions', to='tenancy.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_course_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyLesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('lesson_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('checklist', 'Checklist'), ('download', 'Download')], default='article', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('video_url', models.URLField(blank=True, default='', max_length=1024)),
                ('download_url', models.URLField(blank=True, default='', max_length=1024)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.academycourse')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyLessonProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=16)),
                ('percent_complete', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='academy.academycourse')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='academy.academylesson')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_lesson_progress', to='tenancy.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademySavedContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='academy.academycourse')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='academy.academylesson')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_saved', to='tenancy.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='academycourse',
            index=models.Index(fields=['status', 'section_key', 'sort_order'], name='academy_aca_status_3c77c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='academycoursecompletion',
            constraint=models.UniqueConstraint(fields=('location', 'user', 'course'), name='unique_academy_course_completion'),
        ),
        migrations.AddIndex(
            model_name='academylesson',
            index=models.Index(fields=['course', 'status', 'sort_order'], name='academy_aca_course__a97786_idx'),
        ),
        migrations.AddIndex(
            model_name='academylessonprogress',
            index=models.Index(fields=['location', 'user', 'course'], name='academy_aca_locatio_9bcf86_idx'),
        ),
        migrations.AddConstraint(
            model_name='academylessonprogress',
            constraint=models.UniqueConstraint(fields=('location', 'user', 'lesson'), name='unique_academy_lesson_progress'),
        ),
        migrations.AddConstraint(
            model_name='academysavedcontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('lesson__isnull', True)), models.Q(('course__isnull', True), ('lesson__isnull', False)), _connector='OR'), name='academy_saved_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='academysavedcontent',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('location', 'user', 'course'), name='unique_academy_saved_course'),
        ),
        migrations.AddConstraint(
            model_name='academysavedcontent',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('location', 'user', 'lesson'), name='unique_academy_saved_lesson'),
        ),
    ]
