# Generated by Django 5.1.4 on 2026-07-20 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ghl_file_id', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.URLField(max_length=1024)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
