# Generated by Django 5.1.4 on 2026-07-17 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSyncState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('daily_from', models.DateField(blank=True, null=True)),
                ('daily_to', models.DateField(blank=True, null=True)),
                ('days_upserted', models.PositiveIntegerField(default=0)),
                ('campaigns_upserted', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='idle', help_text='idle | syncing | success | error', max_length=32)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_sync_state', to='tenancy.location')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaAdDailyStat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('ad_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('cpc', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('reach', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('cost_per_result_breakdown', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ad_daily_stats', to='tenancy.location')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['location', 'date'], name='roi_metaadd_locatio_a8b6c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'date'), name='unique_meta_daily_stat_per_location_date')],
            },
        ),
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(db_index=True, max_length=64)),
                ('ad_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_campaigns', to='tenancy.location')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['location', 'status'], name='roi_metacam_locatio_dc4523_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'campaign_id'), name='unique_meta_campaign_per_location')],
            },
        ),
    ]
