# Generated by Django 5.1.4 on 2026-07-17 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPeriodSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('cpc', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('raw_totals', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_period_snapshots', to='tenancy.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'period_start', 'period_end'], name='roi_metaper_locatio_a8cc38_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'period_start', 'period_end'), name='unique_meta_period_snapshot')],
            },
        ),
    ]
