# Generated by Django 5.1.4 on 2026-07-17 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0002_metaperiodsnapshot'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSyncState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('daily_from', models.DateField(blank=True, null=True)),
                ('daily_to', models.DateField(blank=True, null=True)),
                ('days_upserted', models.PositiveIntegerField(default=0)),
                ('campaigns_upserted', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='idle', help_text='idle | syncing | success | error', max_length=32)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sync_state', to='tenancy.location')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleAdDailyStat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cpc', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ad_daily_stats', to='tenancy.location')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['location', 'date'], name='roi_googlea_locatio_2c2a1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'date'), name='unique_google_daily_stat_per_location_date')],
            },
        ),
        migrations.CreateModel(
            name='GoogleCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(db_index=True, max_length=64)),
                ('customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cpc', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('metrics_start', models.DateField(blank=True, null=True)),
                ('metrics_end', models.DateField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_campaigns', to='tenancy.location')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['location', 'status'], name='roi_googlec_locatio_038517_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'campaign_id'), name='unique_google_campaign_per_location')],
            },
        ),
        migrations.CreateModel(
            name='GooglePeriodSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cpc', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('raw_totals', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_period_snapshots', to='tenancy.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'period_start', 'period_end'], name='roi_googlep_locatio_fe93ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'period_start', 'period_end'), name='unique_google_period_snapshot')],
            },
        ),
    ]
