# Generated by Django 5.1.4 on 2026-07-22 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0003_google_ads_models'),
        ('tenancy', '0002_locationmediafolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoiCrmSetup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_id', models.CharField(blank=True, default='', max_length=64)),
                ('pipeline_name', models.CharField(blank=True, default='', max_length=255)),
                ('setup_status', models.CharField(choices=[('needs_pipeline', 'Needs pipeline'), ('confirmed', 'Confirmed')], db_index=True, default='needs_pipeline', max_length=32)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('opportunities_synced', models.PositiveIntegerField(default=0)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('sync_status', models.CharField(default='idle', help_text='idle | syncing | success | error', max_length=32)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roi_crm_setup', to='tenancy.location')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GhlOpportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ghl_opportunity_id', models.CharField(db_index=True, max_length=64)),
                ('pipeline_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('pipeline_stage_id', models.CharField(blank=True, default='', max_length=64)),
                ('pipeline_stage_name', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('abandoned', 'Abandoned'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('status_raw', models.CharField(blank=True, default='', max_length=64)),
                ('monetary_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_raw', models.CharField(blank=True, default='', max_length=255)),
                ('source_channel', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('contact_id', models.CharField(blank=True, default='', max_length=64)),
                ('ghl_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ghl_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_change_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghl_opportunities', to='tenancy.location')),
            ],
            options={
                'ordering': ['-ghl_created_at', '-created_at'],
                'indexes': [models.Index(fields=['location', 'status', 'source_channel'], name='roi_ghloppo_locatio_1bff51_idx'), models.Index(fields=['location', 'pipeline_id', 'status'], name='roi_ghloppo_locatio_4b5218_idx'), models.Index(fields=['location', 'last_status_change_at'], name='roi_ghloppo_locatio_2f60db_idx'), models.Index(fields=['location', 'ghl_created_at'], name='roi_ghloppo_locatio_cbd558_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'ghl_opportunity_id'), name='unique_ghl_opportunity_per_location')],
            },
        ),
    ]
