# Generated by Django 5.2.11 on 2026-07-31 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_membership_permission_overrides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityChannel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("company", "Company Channel"),
                            ("service_pilot", "Service Pilot Channel"),
                            ("industry", "Industry Group"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_channels_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for company channels; null for platform (SP / industry).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_channels",
                        to="tenancy.location",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CommunityChannelMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="community.communitychannel",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_channel_memberships",
                        to="tenancy.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_channel_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=16,
                    ),
                ),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="community.communitychannel",
                    ),
                ),
                (
                    "thread_root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="community.communitymessage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="communitychannel",
            index=models.Index(
                fields=["channel_type", "is_archived"],
                name="community_c_channel_5f53f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communitychannel",
            index=models.Index(
                fields=["location", "channel_type"],
                name="community_c_locatio_7cdc7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communitychannel",
            index=models.Index(
                fields=["-updated_at"], name="community_c_updated_f6355c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="communitychannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location__isnull", False)),
                fields=("location", "slug"),
                name="unique_community_channel_slug_per_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="communitychannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location__isnull", True)),
                fields=("slug",),
                name="unique_community_platform_channel_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="communitychannelmember",
            index=models.Index(
                fields=["channel", "user"], name="community_c_channel_7aa5b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitychannelmember",
            index=models.Index(
                fields=["user", "left_at"], name="community_c_user_id_2029b2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="communitychannelmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("channel", "user"),
                name="unique_active_community_channel_member",
            ),
        ),
        migrations.AddIndex(
            model_name="communitymessage",
            index=models.Index(
                fields=["channel", "-created_at"], name="community_c_channel_2fb9b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymessage",
            index=models.Index(
                fields=["channel", "status", "-created_at"],
                name="community_c_channel_62a857_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communitymessage",
            index=models.Index(
                fields=["thread_root", "created_at"],
                name="community_c_thread__03acce_idx",
            ),
        ),
    ]
