# Generated by Django 5.1.4 on 2026-07-31 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_community_hub_channels"),
        ("tenancy", "0003_membership_permission_overrides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityDmConversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "participant_pair_key",
                    models.CharField(db_index=True, max_length=80),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_message_preview",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_dms_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_dm_conversations",
                        to="tenancy.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityDmMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=16,
                    ),
                ),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_dm_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="community.communitydmconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityDmParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("is_muted", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="community.communitydmconversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_dm_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityPinnedMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="community.communitychannel",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="community.communitymessage",
                    ),
                ),
                (
                    "pinned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_pins_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunitySavedMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_saved_messages",
                        to="tenancy.location",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="community.communitymessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_saved_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityUserAvailability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("away", "Away"),
                            ("offline", "Offline"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=16,
                    ),
                ),
                (
                    "status_message",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_availability",
                        to="tenancy.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="communitydmconversation",
            index=models.Index(
                fields=["location", "-last_message_at"],
                name="community_c_locatio_d86323_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="communitydmconversation",
            constraint=models.UniqueConstraint(
                fields=("location", "participant_pair_key"),
                name="unique_community_dm_pair_per_location",
            ),
        ),
        migrations.AddIndex(
            model_name="communitydmmessage",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="community_c_convers_a23551_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communitydmmessage",
            index=models.Index(
                fields=["conversation", "status", "-created_at"],
                name="community_c_convers_e2991d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="communitydmparticipant",
            constraint=models.UniqueConstraint(
                fields=("conversation", "user"), name="unique_community_dm_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypinnedmessage",
            index=models.Index(
                fields=["channel", "is_active", "-created_at"],
                name="community_c_channel_f91417_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="communitypinnedmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("channel", "message"),
                name="unique_active_community_pin",
            ),
        ),
        migrations.AddIndex(
            model_name="communitysavedmessage",
            index=models.Index(
                fields=["user", "location", "-created_at"],
                name="community_c_user_id_0c1430_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="communitysavedmessage",
            constraint=models.UniqueConstraint(
                fields=("user", "message"), name="unique_community_saved_message"
            ),
        ),
        migrations.AddIndex(
            model_name="communityuseravailability",
            index=models.Index(
                fields=["location", "status"], name="community_c_locatio_030642_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="communityuseravailability",
            constraint=models.UniqueConstraint(
                fields=("location", "user"),
                name="unique_community_availability_per_location_user",
            ),
        ),
    ]
