# Generated by Django 5.2.11 on 2026-08-03 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_community_phase2_availability_dms_pins"),
        ("tenancy", "0003_membership_permission_overrides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityChannelNotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_level",
                    models.CharField(
                        choices=[
                            ("all_messages", "All messages"),
                            ("mentions_and_replies", "Mentions & replies"),
                            ("none", "None"),
                        ],
                        default="mentions_and_replies",
                        max_length=32,
                    ),
                ),
                ("notify_thread_replies", models.BooleanField(default=True)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="community.communitychannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["channel", "notification_level"],
                        name="community_c_channel_4aea6f_idx",
                    ),
                    models.Index(
                        fields=["user", "is_muted"],
                        name="community_c_user_id_603299_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "channel"),
                        name="unique_community_channel_notification_pref",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityDmReaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reaction_key", models.CharField(db_index=True, max_length=32)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.communitydmmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_dm_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["message", "reaction_key"],
                        name="community_c_message_2a5dad_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user", "reaction_key"),
                        name="unique_community_dm_message_reaction",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityMessageReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, default="other", max_length=64),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Reporter's active location when filing the report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_message_reports",
                        to="tenancy.location",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.communitymessage",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_message_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="community_c_status_798f2d_idx",
                    ),
                    models.Index(
                        fields=["location", "status", "-created_at"],
                        name="community_c_locatio_68792d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "reporter"),
                        name="unique_community_message_report_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityNotification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("new_message", "New message"),
                            ("mention", "Mention"),
                            ("thread_reply", "Thread reply"),
                            ("dm_message", "Direct message"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("excerpt", models.CharField(blank=True, default="", max_length=200)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_notifications_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="community.communitychannel",
                    ),
                ),
                (
                    "dm_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="community.communitydmconversation",
                    ),
                ),
                (
                    "dm_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="community.communitydmmessage",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="community.communitymessage",
                    ),
                ),
                (
                    "thread_root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_notifications",
                        to="community.communitymessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="community_c_user_id_792779_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="community_c_user_id_f3a191_idx",
                    ),
                    models.Index(
                        fields=["user", "channel", "is_read"],
                        name="community_c_user_id_d387f6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("message__isnull", False)),
                        fields=("user", "message", "reason"),
                        name="unique_community_notif_user_message_reason",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("dm_message__isnull", False)),
                        fields=("user", "dm_message", "reason"),
                        name="unique_community_notif_user_dm_message_reason",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityReaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reaction_key", models.CharField(db_index=True, max_length=32)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.communitymessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["message", "reaction_key"],
                        name="community_c_message_b18da8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user", "reaction_key"),
                        name="unique_community_message_reaction",
                    )
                ],
            },
        ),
    ]
