# Generated by Django 5.2.11 on 2026-08-05 10:39

from django.db import migrations, models


def forwards_normalize_levels(apps, schema_editor):
    Pref = apps.get_model("community", "CommunityChannelNotificationPreference")
    Pref.objects.filter(notification_level="mentions_and_replies").update(
        notification_level="all_messages",
        is_muted=False,
    )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_community_phase3_notifications_reactions_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitychannelnotificationpreference",
            name="notification_level",
            field=models.CharField(
                choices=[
                    ("all_messages", "All messages"),
                    ("mentions_and_replies", "Mentions & replies"),
                    ("none", "None"),
                ],
                default="all_messages",
                max_length=32,
            ),
        ),
        migrations.RunPython(forwards_normalize_levels, backwards_noop),
    ]
